services:
  app:
    extends:
      file: docker-compose.app.yaml
      service: app-air
    container_name: app
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    networks:
      - app_network
  
volumes:
  db_data:

networks:
  app_network:
