// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/elements": {
            "get": {
                "description": "Get a list of all available elements",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Elements"
                ],
                "summary": "Get all elements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/search.ElementResponse"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the application is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/search/bfs": {
            "get": {
                "description": "Search the recipe of elements using BFS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "BFS search handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query parameter",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1",
                        "description": "Number of recipes to return",
                        "name": "num",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "false",
                        "description": "Live update",
                        "name": "live",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/search.SearchResponse"
                        }
                    }
                }
            }
        },
        "/search/bidirectional": {
            "get": {
                "description": "Search the recipe of elements using Bidirectional Search.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Bidirectional search handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target element to search for",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1",
                        "description": "Chooses the Nth found meeting node (sorted) to construct the path",
                        "name": "num",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful search operation.",
                        "schema": {
                            "$ref": "#/definitions/search.SearchResponse"
                        }
                    }
                }
            }
        },
        "/search/dfs": {
            "get": {
                "description": "Search the recipe of elements using DFS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "DFS search handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query parameter",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1",
                        "description": "Number of recipes to return",
                        "name": "num",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "false",
                        "description": "Live update",
                        "name": "live",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/search.SearchResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "scraper.TreeNode": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scraper.TreeNode"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "imageSrc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "search.ElementResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "search.SearchResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/scraper.TreeNode"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
